### ISSUE TITLE
与知乎网页的冲突

### ISSUE THREAD

**Issue by wangjiezhe** [slc3a2/dimmer#9]
在启用扩展的情况下，点开知乎评论区的图片进行放大，然后再点击图片缩小，此时页面会卡住无法滚动。

点击正文里面的图片不会出现这种情况。

**Comment by liang7hi** [comment]
当打开关灯插件时，点击知乎评论中的图片放大查看后，然后关闭，这时 html 的 body 的 css:
```css
body: {
   overflow: hidden;
}
```
关闭关灯插件后：重复上述操作，css为：
```css
body: {
   overflow: auto;
}
```

把 body 的 overflow 属性改为 auto，就可以滚动了。关灯插件没有对当前用户的页面进行任何 overflow 相关的 css 设置，所以暂时不确定是什么逻辑和知乎发生了冲突
